[package]
name = "iata-scraper"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12", features = ["gzip", "deflate", "brotli", "rustls-tls"] }
scraper = "0.19"
csv = "1.3"
futures = "0.3"
